GDAL_CACHEMAX=2560 gdaldem color-relief  -co COMPRESS=LZW -alpha -of GTiff  ./data/treecover_tifs/2018.tif treecover-colortable.txt ./data/treecover_tifs/2018_rgb.tif && GDAL_CACHEMAX=2560 rio mbtiles ./data/treecover_tifs/2018_rgb.tif ./data/treecover_tifs/yforest_cover_2018.mbtiles  --format WEBP --co LOSSLESS=TRUE --co QUALITY=60 --progress-bar --zoom-levels 0..14 --tile-size 512 && ./pmtiles convert ./data/treecover_tifs/yforest_cover_2018.mbtiles ./data/treecover_tifs/forest_cover_2018.pmtiles && \
GDAL_CACHEMAX=2560 gdaldem color-relief  -co COMPRESS=LZW -alpha -of GTiff  ./data/treecover_tifs/2019.tif treecover-colortable.txt ./data/treecover_tifs/2019_rgb.tif && GDAL_CACHEMAX=2560 rio mbtiles ./data/treecover_tifs/2019_rgb.tif ./data/treecover_tifs/yforest_cover_2019.mbtiles  --format WEBP --co LOSSLESS=TRUE --co QUALITY=60 --progress-bar --zoom-levels 0..14 --tile-size 512 && ./pmtiles convert ./data/treecover_tifs/yforest_cover_2019.mbtiles ./data/treecover_tifs/forest_cover_2019.pmtiles && \
GDAL_CACHEMAX=2560 gdaldem color-relief  -co COMPRESS=LZW -alpha -of GTiff  ./data/treecover_tifs/2020.tif treecover-colortable.txt ./data/treecover_tifs/2020_rgb.tif && GDAL_CACHEMAX=2560 rio mbtiles ./data/treecover_tifs/2020_rgb.tif ./data/treecover_tifs/yforest_cover_2020.mbtiles  --format WEBP --co LOSSLESS=TRUE --co QUALITY=60 --progress-bar --zoom-levels 0..14 --tile-size 512 && ./pmtiles convert ./data/treecover_tifs/yforest_cover_2020.mbtiles ./data/treecover_tifs/forest_cover_2020.pmtiles && \
GDAL_CACHEMAX=2560 gdaldem color-relief  -co COMPRESS=LZW -alpha -of GTiff  ./data/treecover_tifs/2021.tif treecover-colortable.txt ./data/treecover_tifs/2021_rgb.tif && GDAL_CACHEMAX=2560 rio mbtiles ./data/treecover_tifs/2021_rgb.tif ./data/treecover_tifs/yforest_cover_2021.mbtiles  --format WEBP --co LOSSLESS=TRUE --co QUALITY=60 --progress-bar --zoom-levels 0..14 --tile-size 512 && ./pmtiles convert ./data/treecover_tifs/yforest_cover_2021.mbtiles ./data/treecover_tifs/forest_cover_2021.pmtiles && \
GDAL_CACHEMAX=2560 gdaldem color-relief  -co COMPRESS=LZW -alpha -of GTiff  ./data/treecover_tifs/2022.tif treecover-colortable.txt ./data/treecover_tifs/2022_rgb.tif && GDAL_CACHEMAX=2560 rio mbtiles ./data/treecover_tifs/2022_rgb.tif ./data/treecover_tifs/yforest_cover_2022.mbtiles  --format WEBP --co LOSSLESS=TRUE --co QUALITY=60 --progress-bar --zoom-levels 0..14 --tile-size 512 && ./pmtiles convert ./data/treecover_tifs/yforest_cover_2022.mbtiles ./data/treecover_tifs/forest_cover_2022.pmtiles && \
GDAL_CACHEMAX=2560 gdaldem color-relief  -co COMPRESS=LZW -alpha -of GTiff  ./data/treecover_tifs/2023.tif treecover-colortable.txt ./data/treecover_tifs/2023_rgb.tif && GDAL_CACHEMAX=2560 rio mbtiles ./data/treecover_tifs/2023_rgb.tif ./data/treecover_tifs/yforest_cover_2023.mbtiles  --format WEBP --co LOSSLESS=TRUE --co QUALITY=60 --progress-bar --zoom-levels 0..14 --tile-size 512 && ./pmtiles convert ./data/treecover_tifs/yforest_cover_2023.mbtiles ./data/treecover_tifs/forest_cover_2023.pmtiles && \
GDAL_CACHEMAX=2560 gdaldem color-relief  -co COMPRESS=LZW -alpha -of GTiff  ./data/treecover_tifs/2024.tif treecover-colortable.txt ./data/treecover_tifs/2024_rgb.tif && GDAL_CACHEMAX=2560 rio mbtiles ./data/treecover_tifs/2024_rgb.tif ./data/treecover_tifs/yforest_cover_2024.mbtiles  --format WEBP --co LOSSLESS=TRUE --co QUALITY=60 --progress-bar --zoom-levels 0..14 --tile-size 512 && ./pmtiles convert ./data/treecover_tifs/yforest_cover_2024.mbtiles ./data/treecover_tifs/forest_cover_2024.pmtiles


GDAL_CACHEMAX=2560 gdaldem color-relief  -co COMPRESS=LZW -alpha -of GTiff  ./data/canopydensity/2013_fcd_rcd.img canopydensity-colormap.txt ./data/canopydensity/2013_rgb.tif && GDAL_CACHEMAX=2560 rio mbtiles ./data/canopydensity/2013_rgb.tif ./data/canopydensity/canopy_density_2013.mbtiles  --format WEBP --co LOSSLESS=TRUE --co QUALITY=60 --progress-bar --zoom-levels 0..14 --tile-size 512 && ./pmtiles convert ./data/canopydensity/canopy_density_2013.mbtiles ./data/canopydensity/canopy_density_2013.pmtiles && \ 
GDAL_CACHEMAX=2560 gdaldem color-relief  -co COMPRESS=LZW -alpha -of GTiff  ./data/canopydensity/2014_fcd_rcd.img canopydensity-colormap.txt ./data/canopydensity/2014_rgb.tif && GDAL_CACHEMAX=2560 rio mbtiles ./data/canopydensity/2014_rgb.tif ./data/canopydensity/canopy_density_2014.mbtiles  --format WEBP --co LOSSLESS=TRUE --co QUALITY=60 --progress-bar --zoom-levels 0..14 --tile-size 512 && ./pmtiles convert ./data/canopydensity/canopy_density_2014.mbtiles ./data/canopydensity/canopy_density_2014.pmtiles && \ 
GDAL_CACHEMAX=2560 gdaldem color-relief  -co COMPRESS=LZW -alpha -of GTiff  ./data/canopydensity/2015_fcd_rcd.img canopydensity-colormap.txt ./data/canopydensity/2015_rgb.tif && GDAL_CACHEMAX=2560 rio mbtiles ./data/canopydensity/2015_rgb.tif ./data/canopydensity/canopy_density_2015.mbtiles  --format WEBP --co LOSSLESS=TRUE --co QUALITY=60 --progress-bar --zoom-levels 0..14 --tile-size 512 && ./pmtiles convert ./data/canopydensity/canopy_density_2015.mbtiles ./data/canopydensity/canopy_density_2015.pmtiles && \ 
GDAL_CACHEMAX=2560 gdaldem color-relief  -co COMPRESS=LZW -alpha -of GTiff  ./data/canopydensity/2016_fcd_rcd.img canopydensity-colormap.txt ./data/canopydensity/2016_rgb.tif && GDAL_CACHEMAX=2560 rio mbtiles ./data/canopydensity/2016_rgb.tif ./data/canopydensity/canopy_density_2016.mbtiles  --format WEBP --co LOSSLESS=TRUE --co QUALITY=60 --progress-bar --zoom-levels 0..14 --tile-size 512 && ./pmtiles convert ./data/canopydensity/canopy_density_2016.mbtiles ./data/canopydensity/canopy_density_2016.pmtiles && \ 
GDAL_CACHEMAX=2560 gdaldem color-relief  -co COMPRESS=LZW -alpha -of GTiff  ./data/canopydensity/2017_fcd_rcd.img canopydensity-colormap.txt ./data/canopydensity/2017_rgb.tif && GDAL_CACHEMAX=2560 rio mbtiles ./data/canopydensity/2017_rgb.tif ./data/canopydensity/canopy_density_2017.mbtiles  --format WEBP --co LOSSLESS=TRUE --co QUALITY=60 --progress-bar --zoom-levels 0..14 --tile-size 512 && ./pmtiles convert ./data/canopydensity/canopy_density_2017.mbtiles ./data/canopydensity/canopy_density_2017.pmtiles && \ 
GDAL_CACHEMAX=2560 gdaldem color-relief  -co COMPRESS=LZW -alpha -of GTiff  ./data/canopydensity/2018_fcd_rcd.img canopydensity-colormap.txt ./data/canopydensity/2018_rgb.tif && GDAL_CACHEMAX=2560 rio mbtiles ./data/canopydensity/2018_rgb.tif ./data/canopydensity/canopy_density_2018.mbtiles  --format WEBP --co LOSSLESS=TRUE --co QUALITY=60 --progress-bar --zoom-levels 0..14 --tile-size 512 && ./pmtiles convert ./data/canopydensity/canopy_density_2018.mbtiles ./data/canopydensity/canopy_density_2018.pmtiles && \ 
GDAL_CACHEMAX=2560 gdaldem color-relief  -co COMPRESS=LZW -alpha -of GTiff  ./data/canopydensity/2019_fcd_rcd.img canopydensity-colormap.txt ./data/canopydensity/2019_rgb.tif && GDAL_CACHEMAX=2560 rio mbtiles ./data/canopydensity/2019_rgb.tif ./data/canopydensity/canopy_density_2019.mbtiles  --format WEBP --co LOSSLESS=TRUE --co QUALITY=60 --progress-bar --zoom-levels 0..14 --tile-size 512 && ./pmtiles convert ./data/canopydensity/canopy_density_2019.mbtiles ./data/canopydensity/canopy_density_2019.pmtiles && \ 
GDAL_CACHEMAX=2560 gdaldem color-relief  -co COMPRESS=LZW -alpha -of GTiff  ./data/canopydensity/2020_fcd_rcd.img canopydensity-colormap.txt ./data/canopydensity/2020_rgb.tif && GDAL_CACHEMAX=2560 rio mbtiles ./data/canopydensity/2020_rgb.tif ./data/canopydensity/canopy_density_2020.mbtiles  --format WEBP --co LOSSLESS=TRUE --co QUALITY=60 --progress-bar --zoom-levels 0..14 --tile-size 512 && ./pmtiles convert ./data/canopydensity/canopy_density_2020.mbtiles ./data/canopydensity/canopy_density_2020.pmtiles && \ 
GDAL_CACHEMAX=2560 gdaldem color-relief  -co COMPRESS=LZW -alpha -of GTiff  ./data/canopydensity/2021_fcd_rcd.img canopydensity-colormap.txt ./data/canopydensity/2021_rgb.tif && GDAL_CACHEMAX=2560 rio mbtiles ./data/canopydensity/2021_rgb.tif ./data/canopydensity/canopy_density_2021.mbtiles  --format WEBP --co LOSSLESS=TRUE --co QUALITY=60 --progress-bar --zoom-levels 0..14 --tile-size 512 && ./pmtiles convert ./data/canopydensity/canopy_density_2021.mbtiles ./data/canopydensity/canopy_density_2021.pmtiles && \ 
GDAL_CACHEMAX=2560 gdaldem color-relief  -co COMPRESS=LZW -alpha -of GTiff  ./data/canopydensity/2022_fcd_rcd.img canopydensity-colormap.txt ./data/canopydensity/2022_rgb.tif && GDAL_CACHEMAX=2560 rio mbtiles ./data/canopydensity/2022_rgb.tif ./data/canopydensity/canopy_density_2022.mbtiles  --format WEBP --co LOSSLESS=TRUE --co QUALITY=60 --progress-bar --zoom-levels 0..14 --tile-size 512 && ./pmtiles convert ./data/canopydensity/canopy_density_2022.mbtiles ./data/canopydensity/canopy_density_2022.pmtiles && \ 
GDAL_CACHEMAX=2560 gdaldem color-relief  -co COMPRESS=LZW -alpha -of GTiff  ./data/canopydensity/2023_fcd_rcd.img canopydensity-colormap.txt ./data/canopydensity/2023_rgb.tif && GDAL_CACHEMAX=2560 rio mbtiles ./data/canopydensity/2023_rgb.tif ./data/canopydensity/canopy_density_2023.mbtiles  --format WEBP --co LOSSLESS=TRUE --co QUALITY=60 --progress-bar --zoom-levels 0..14 --tile-size 512 && ./pmtiles convert ./data/canopydensity/canopy_density_2023.mbtiles ./data/canopydensity/canopy_density_2023.pmtiles && \ 
GDAL_CACHEMAX=2560 gdaldem color-relief  -co COMPRESS=LZW -alpha -of GTiff  ./data/canopydensity/2024_fcd_rcd.img canopydensity-colormap.txt ./data/canopydensity/2024_rgb.tif && GDAL_CACHEMAX=2560 rio mbtiles ./data/canopydensity/2024_rgb.tif ./data/canopydensity/canopy_density_2024.mbtiles  --format WEBP --co LOSSLESS=TRUE --co QUALITY=60 --progress-bar --zoom-levels 0..14 --tile-size 512 && ./pmtiles convert ./data/canopydensity/canopy_density_2024.mbtiles ./data/canopydensity/canopy_density_2024.pmtiles && \ 

rio mbtiles ./data/treecover_tifs/2024_rgb.tif ./data/treecover_tifs/yforest_cover_2024.mbtiles  --format WEBP --co LOSSLESS=TRUE --co QUALITY=60 --progress-bar --zoom-levels 0..14 --tile-size 512

gdal_translate --config GDAL_CACHEMAX 12288 --config GDAL_NUM_THREADS ALL_CPUS -of MBTILES -co "ZLEVEL=9" -co "BLOCKSIZE=512" -co "RESAMPLING=NEAREST" -co "TILE_FORMAT=WEBP" -co "QUALITY=60" -co "COMPRESS=YES" ./data/treecover_tifs/2024_rgb.tif ./data/treecover_tifs/yforest_cover_2024.mbtiles

gdal_translate --config GDAL_CACHEMAX 12288 --config GDAL_NUM_THREADS ALL_CPUS -of MBTILES -co "ZLEVEL=9" -co "BLOCKSIZE=512" -co "RESAMPLING=NEAREST" -co "TILE_FORMAT=WEBP" -co "QUALITY=60" -co "COMPRESS=YES" W:\satsure\dfhms\data\treecover_tifs\2024_rgb.tif W:\satsure\dfhms\data\treecover_tifs\forest_cover_2024.mbtiles
gdal_translate --config GDAL_CACHEMAX 12288 --config GDAL_NUM_THREADS ALL_CPUS -of MBTILES -co "ZLEVEL=9" -co "BLOCKSIZE=512" -co "RESAMPLING=NEAREST" -co "TILE_FORMAT=WEBP" -co "QUALITY=60" -co "COMPRESS=YES" W:\satsure\dfhms\data\treecover_tifs\2024_rgb.tif W:\satsure\dfhms\data\treecover_tifs\forest_cover_2023.mbtiles

gdal_translate --config GDAL_CACHEMAX 12288 --config GDAL_NUM_THREADS ALL_CPUS -of MBTILES -ot Int8 -co "ZLEVEL=9" -co "BLOCKSIZE=512" -co "RESAMPLING=NEAREST" -co "TILE_FORMAT=WEBP" -co "QUALITY=60" -co "COMPRESS=YES" W:\satsure\dfhms\data\treecover_tifs\2024_rgb.tif W:\satsure\dfhms\data\treecover_tifs\forest_cover_2022.mbtiles
gdal_translate --config GDAL_CACHEMAX 12288 --config GDAL_NUM_THREADS ALL_CPUS -of MBTILES -co "ZLEVEL=9" -co "BLOCKSIZE=512" -co "RESAMPLING=NEAREST" -co "TILE_FORMAT=WEBP" -co "QUALITY=60" -co "COMPRESS=YES" W:\satsure\dfhms\data\treecover_tifs\2024_rgb.tif W:\satsure\dfhms\data\treecover_tifs\forest_cover_2021.mbtiles
gdal_translate --config GDAL_CACHEMAX 12288 --config GDAL_NUM_THREADS ALL_CPUS -of MBTILES -co "ZLEVEL=9" -co "BLOCKSIZE=512" -co "RESAMPLING=NEAREST" -co "TILE_FORMAT=WEBP" -co "QUALITY=60" -co "COMPRESS=YES" W:\satsure\dfhms\data\treecover_tifs\2024_rgb.tif W:\satsure\dfhms\data\treecover_tifs\forest_cover_2020.mbtiles
gdal_translate --config GDAL_CACHEMAX 12288 --config GDAL_NUM_THREADS ALL_CPUS -of MBTILES -co "ZLEVEL=9" -co "BLOCKSIZE=512" -co "RESAMPLING=NEAREST" -co "TILE_FORMAT=WEBP" -co "QUALITY=60" -co "COMPRESS=YES" W:\satsure\dfhms\data\treecover_tifs\2024_rgb.tif W:\satsure\dfhms\data\treecover_tifs\forest_cover_2019.mbtiles
gdal_translate --config GDAL_CACHEMAX 12288 --config GDAL_NUM_THREADS ALL_CPUS -of MBTILES -co "ZLEVEL=9" -co "BLOCKSIZE=512" -co "RESAMPLING=NEAREST" -co "TILE_FORMAT=WEBP" -co "QUALITY=60" -co "COMPRESS=YES" W:\satsure\dfhms\data\treecover_tifs\2024_rgb.tif W:\satsure\dfhms\data\treecover_tifs\forest_cover_2019.mbtiles
